name: Helm Publish

on:
  push:
    branches: [ che ]

jobs:
  publish-helmchart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Make directory to host app
      run: |
        cd ..
        mkdir helmapp
        pwd
        ls
    - name: Package Helm Charts
      run: | 
        helm package $GITHUB_WORKSPACE/handon/node-web-app
    - name: Move package to helmapp
      run: |
        pwd
        ls
        mv /home/runner/work/demo-publish-helm/demo-publish-helm/handon/*.tgz  /home/runner/work/demo-publish-helm/helmapp        
    - name: list contents of helmapp
      run: |
        cd /home/runner/work/demo-publish-helm/helmapp
        ls
    - name: Create index file
      run: helm repo index /home/runner/work/demo-publish-helm/helmapp
    - name: list contents of helmapp
      run: |
        cd /home/runner/work/demo-publish-helm/helmapp
        ls      
